### ISSUE TITLE
Scraping of Metadata- Relation/s

### ISSUE THREAD

**Issue by simon-donike** [eo4geocourses/UNIBAS_Remote-Sensing-Environment#1]
Hello Nicola,
in order for the automatic scraping of the metadata to work, please make sure to remove the _""_ after the _dc:relation:_ tag. This will prevent the metadata scraper from returning an empty list. But preferably of course, it would be nice if the relations are added, but I'm sure you had that on your schedule already :)

Thanks a lot and kind regards,
Simon 
  
<img width="185" alt="meta" src="https://user-images.githubusercontent.com/65158680/91988996-40d2ee80-ed30-11ea-8c2e-6af35c5ce045.png">

**Comment by nicolacapece** [comment]
Hello Simon,

For now, I have removed them, let me know if it's okay.

Best Regards,
Nicola

**Comment by simon-donike** [comment]
Great, thanks a lot for the quick response. That works, I'm currently trying to include all edge cases within the annotations into the automatic scraping and it sometimes gets close to my technical abilities, so thanks for helping me out with that!
